### ISSUE TITLE
leading zeros not rendered in numbers in helm charts

### ISSUE THREAD

**Issue by wokalski** [arnarg/nixidy#13]
I don't know where the issue lies exactly but when you have charts with values like this:

```
  defaultMode: 0555
```

they end up being rendered as 555.

**Comment by arnarg** [comment]
Seems that YAML supports both octal and decimal notation for integers and nix only does decimal. So unfortunately I think the only way to fix this is to override the `defaultMode` as `365` (`0555` in decimal). It would be useful to provide a helper function to do this conversion in nixidy lib but I can't think of how to implement this quickly in nix.

Docs about `defaultMode`:
```
Optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644. ...
```

See: https://github.com/NixOS/nix/issues/7578

**Comment by wokalski** [comment]
Hmm, we should be converting octal to decimal then automatically. The parsing is not handled by nxiidy, is it?

**Comment by arnarg** [comment]
Yeah you're correct. What's the resource kind that's causing issues?

**Comment by arnarg** [comment]
Oh wait! I just need to update nix-kube-generators in my flake lock file! https://github.com/farcaller/nix-kube-generators/commit/2a1fe17dd9eaf0990239a44576ffb46db12d6b57

**Comment by wokalski** [comment]
nice. in this case it was Kustomization  I believe but it's probably applicable to all yamls 😄.

Great find thank you.

**Comment by arnarg** [comment]
I made a new release `v0.2.0` which should address this issue. Please let me know if it doesn't.

**Comment by wokalski** [comment]
thanks, I'll let you know!
