### ISSUE TITLE
ApplicationSets for Application Generators

### ISSUE THREAD

**Issue by mrtz-j** [arnarg/nixidy#15]
The ability to create ApplicationSets would be nice for pull request generators, e.g. to spin up review applications using a WebHook listing on a repository. 

I'm currently solving this by writing it in yaml and adding it manually.

Thanks for the cool project.

**Comment by arnarg** [comment]
Thanks for the issue. Do you mean to add type definition for ApplicationSet so you can define then with `resources.applicationSets`?

If that's the case I should be able to add this rather quickly with the code generator from CRDs.

**Comment by mrtz-j** [comment]
Yes, that's exactly what I'm looking for.

**Comment by arnarg** [comment]
The CRD for ApplicationSet doesn't adhere to some assumptions made in my generator script so I'll have try to fix this in the coming days.

**Comment by arnarg** [comment]
I managed to fix the code generator to work with ApplicationSet and it's available on main now. Please test it out and let me know if something doesn't work.
