### ISSUE TITLE
Error Generating Types from Kyverno CRDs

### ISSUE THREAD

**Issue by mrtz-j** [arnarg/nixidy#16]
I'm trying to use the generators to generate typed resource options from the [kyverno crds](https://github.com/kyverno/kyverno/tree/main/config/crds/kyverno), but I'm getting the `error: attribute 'type' missing` on some of the crds.

<details><summary>complete error message</summary>
<p>

```console
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'k8s-kyverno-gen.nix'
         whose name attribute is located at /nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildCommand' of derivation 'k8s-kyverno-gen.nix'

         at /nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source/pkgs/build-support/trivial-builders/default.nix:59:16:

           58|         enableParallelBuilding = true;
           59|         inherit buildCommand name;
             |                ^
           60|         passAsFile = [ "buildCommand" ]

       error: attribute 'type' missing

       at /nix/store/isaang8p0fi3m0an2kgivnb097a5br60-source/pkgs/generators/jsonschema.nix:154:29:

          153|                     # if property has an array type
          154|                     else if property.type == "array"
             |                             ^
          155|                     then
```

</p>
</details> 

For example the [updaterequests](https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno/kyverno.io_updaterequests.yaml) crds work, but [policies](https://github.com/kyverno/kyverno/blob/main/config/crds/kyverno/kyverno.io_policies.yaml) crds fail.

Is there a good way to debug the generator and fix it or rewrite the type in the crds?

**Comment by mrtz-j** [comment]
That was indeed the problem, I'll add a Github Action for automatically running `nix flake update` now 😅 Setting up cilium and kyverno policies has been a breeze with nixidy, thanks again.

**Comment by arnarg** [comment]
Perfect! I'll close the issue then :)

I'm glad it's helpful!
