### ISSUE TITLE
applications.<name>.name has no effect

### ISSUE THREAD

**Issue by juselius** [arnarg/nixidy#17]
First off, what a fantastic project nixidy is! Love it!

I noticed that the `applications.<name>.name` option has no effect on anything, as far as I can tell. The question is really whether this option is needed, since the name can easily be tweaked using nix string interpolation (e.g. `applications.${env}-foo = { ... }`.

**Comment by arnarg** [comment]
Thanks for the issue and I'm glad you like the project :)

I think the option can be useful if you want to force change the name of an application that was already defined in another module. I added this option initially before I had implemented any unit tests and then forgot to make sure it works as expected. 

I hope I can take some time to fix this soon.

**Comment by juselius** [comment]
Ah, yes I see. I'll PR if I fix it first :)

**Comment by arnarg** [comment]
The fix was simpler than I expected so I could quickly fix it. I created a new release v0.5.0 including this bug fix. Thanks for the report!

**Comment by juselius** [comment]
Thanks for fixing it so quickly @arnarg!
