### ISSUE TITLE
Make removeLabels applies to deployments.<name>.spec.template.metadata.labels

### ISSUE THREAD

**Issue by liyangau** [arnarg/nixidy#27]
Hi,

Currently the `removeLabels` only applies to the `manifest.metadata`.

```nix
helm.transformer = map (
  lib.kube.removeLabels [
    "app.kubernetes.io/version"
    "helm.sh/chart"
    "app.kubernetes.io/managed-by"
  ]
);
```

It will be nice it also removes  `applications.<name>.resources.deployments.<name>.spec.template.metadata.labels`.

**Comment by arnarg** [comment]
Sounds like a good idea. However, we will need to collect all such cases in different resource types as I'd want the function to work the same accross the board.

Quickly I can think of:
- Deployment
- ReplicaSet
- DaemonSet
- Job
- StatefulSet

But CronJob breaks the pattern and has `.spec.jobTemplate.metadata.labels` and `.spec.jobTemplate.spec.template.metadata.labels`.

**Comment by arnarg** [comment]
I updated the function to do this. Please let me know if something is missing.

**Comment by liyangau** [comment]
> I updated the function to do this. Please let me know if something is missing.

Thanks for adding this. It works as expected.
